services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console UI
    environment:
      MINIO_ROOT_USER: ${aws_access_key}
      MINIO_ROOT_PASSWORD: ${aws_secret_key}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
