appname = content_pipeline
httpport = 8080
runmode = dev

[app]
bucket_name = bucket name here
aws_endpoint = http://localhost:9000
aws_access_key = aws access key here
aws_secret_key = aws secret key here
aws_use_ssl = false
aws_region = aws region here
groq_api_key = Your Groq API Key Here
groq_model = Groq Model Name Here
groq_base_url = Groq Base URL Here
temperature = 0.7
max_output_tokens = 1200