package services

import (
	"bytes"
	"context"
	"regexp"
	"strings"

	openai "github.com/sashabaranov/go-openai"
	"golang.org/x/net/html"
)

// SEOResponse represents the final processed SEO title and description to be returned to the client.
type SEOResponse struct {
	Title       string `json:"title"`
	Description string `json:"description"`
}

// RawSEOOutput represents the raw output generated by the LLM before any processing or normalization.
type RawSEOOutput struct {
	RawTitle       string `json:"raw_title"`
	RawDescription string `json:"raw_description"`
}

// LLMConfig holds configuration parameters for the LLM generation process, such as temperature and max output tokens.
type LLMConfig struct {
	Temperature     float32
	MaxOutputTokens int
	TopP            float32
}

type LLMService struct {
	client *openai.Client
	model  string
	config LLMConfig
}

func NewLLMService(client *openai.Client, model string, cfg LLMConfig) *LLMService {
	return &LLMService{
		client: client,
		model:  model,
		config: cfg,
	}
}

// GenerateRawSEO takes title and description prompts, sends them to the LLM, and returns the raw generated outputs.
func (s *LLMService) GenerateRawSEO(titlePrompt, descriptionPrompt string) (RawSEOOutput, error) {
	ctx := context.Background()

	rawTitle, err := s.generate(ctx, titlePrompt)
	if err != nil {
		return RawSEOOutput{}, NewServiceError(ErrLLM, "TITLE_GENERATION_FAILED", "title generation failed", err)
	}

	rawDescription, err := s.generate(ctx, descriptionPrompt)
	if err != nil {
		return RawSEOOutput{}, NewServiceError(ErrLLM, "DESCRIPTION_GENERATION_FAILED", "description generation failed", err)
	}

	return RawSEOOutput{
		RawTitle:       rawTitle,
		RawDescription: rawDescription,
	}, nil
}

// generate is a helper method that sends a prompt to the LLM and returns the generated text.
// It handles the OpenAI API request and response parsing, and wraps any errors in a ServiceError with appropriate context.
func (s *LLMService) generate(ctx context.Context, prompt string) (string, error) {
	req := openai.ChatCompletionRequest{
		Model: s.model,
		Messages: []openai.ChatCompletionMessage{
			{
				Role:    openai.ChatMessageRoleUser,
				Content: prompt,
			},
		},
		Temperature: s.config.Temperature,
		MaxTokens:   s.config.MaxOutputTokens,
	}

	resp, err := s.client.CreateChatCompletion(ctx, req)
	if err != nil {
		return "", NewServiceError(ErrLLM, "LLM_REQUEST_FAILED", "llm request failed", err)
	}

	if len(resp.Choices) == 0 {
		return "", NewServiceError(ErrLLM, "EMPTY_LLM_RESPONSE", "no choices returned from model", nil)
	}

	return resp.Choices[0].Message.Content, nil
}

// ProcessRawSEO takes the raw output from the LLM and processes it to produce clean, normalized SEO title and description.
// It performs operations such as stripping HTML tags from the title and normalizing the description into a well-formed paragraph.
// If the processed title or description is empty after normalization, it returns a ServiceError indicating the issue.
func (s *LLMService) ProcessRawSEO(raw RawSEOOutput) (SEOResponse, error) {
	title := cleanSEOTitle(strings.TrimSpace(raw.RawTitle))
	description := clecleanSEODescription(raw.RawDescription)

	if title == "" {
		return SEOResponse{}, NewServiceError(ErrProcessing, "EMPTY_PROCESSED_TITLE", "processed title is empty", nil)
	}
	if description == "" {
		return SEOResponse{}, NewServiceError(ErrProcessing, "EMPTY_PROCESSED_DESCRIPTION", "processed description is empty", nil)
	}

	return SEOResponse{
		Title:       title,
		Description: description,
	}, nil
}

// cleanSEOTitle takes an input string that may contain extraneous information and attempts to extract a clean SEO title.
// It looks for the first quoted substring and returns it as the title, or if no quotes are found, it returns the input string with normalized whitespace.
// This is a simple heuristic to handle cases where the LLM might return a title in quotes or with additional context.
func cleanSEOTitle(input string) string {
	var firstQuoteRe = regexp.MustCompile(`["']([^"']+)["']`)

	// normalize whitespace
	text := strings.Join(strings.Fields(input), " ")

	// extract first quoted part
	if m := firstQuoteRe.FindStringSubmatch(text); len(m) == 2 {
		return strings.TrimSpace(m[1])
	}

	return strings.TrimSpace(text)
}

// cleanSingleP takes an input string that may contain HTML content and extracts the content of the first <p> tag it finds.
// It returns a string that consists of the content of that <p> tag wrapped in a single <p> tag, effectively normalizing the description to a single paragraph format.
// If no <p> tag is found, it returns an empty string. The function uses the html package to parse the input and traverse the DOM tree to find the first <p> element.
func clecleanSEODescription(input string) string {
	doc, err := html.Parse(strings.NewReader(input))
	if err != nil {
		return ""
	}

	var firstP *html.Node

	var find func(*html.Node)
	find = func(n *html.Node) {
		if n.Type == html.ElementNode && n.Data == "p" && firstP == nil {
			firstP = n
			return
		}
		for c := n.FirstChild; c != nil; c = c.NextSibling {
			find(c)
		}
	}

	find(doc)

	if firstP == nil {
		return ""
	}

	var buf bytes.Buffer
	for c := firstP.FirstChild; c != nil; c = c.NextSibling {
		html.Render(&buf, c)
	}

	content := strings.TrimSpace(buf.String())

	return "<p>" + content + "</p>"
}
